import { Translation, Asset, Liability } from './types';

export const CURRENCIES = [
  { code: 'USD', symbol: '$', name: 'US Dollar (USD)' },
  { code: 'EUR', symbol: '€', name: 'Euro (EUR)' },
  { code: 'GBP', symbol: '£', name: 'British Pound (GBP)' },
  { code: 'INR', symbol: '₹', name: 'Indian Rupee (INR)' },
  { code: 'PKR', symbol: '₨', name: 'Pakistani Rupee (PKR)' },
  { code: 'SAR', symbol: 'SAR', name: 'Saudi Riyal (SAR)' },
  { code: 'AED', symbol: 'AED', name: 'UAE Dirham (AED)' },
  { code: 'CAD', symbol: 'C$', name: 'Canadian Dollar (CAD)' },
  { code: 'AUD', symbol: 'A$', name: 'Australian Dollar (AUD)' },
  { code: 'MYR', symbol: 'RM', name: 'Malaysian Ringgit (MYR)' },
  { code: 'IDR', symbol: 'Rp', name: 'Indonesian Rupiah (IDR)' },
  { code: 'BDT', symbol: '৳', name: 'Bangladeshi Taka (BDT)' },
  { code: 'TRY', symbol: '₺', name: 'Turkish Lira (TRY)' },
];

export const GOLD_NISAB_GRAMS = 87.48;
export const SILVER_NISAB_GRAMS = 612.36;

export const DEFAULT_ASSETS: Asset[] = [
  { id: '1', type: 'cash', name: 'Cash on Hand / Bank', value: 0, isZakatable: true },
  { id: '2', type: 'gold', name: 'Gold (Grams)', value: 0, isZakatable: true },
  { id: '3', type: 'silver', name: 'Silver (Grams)', value: 0, isZakatable: true },
  { id: '4', type: 'jewelry', name: 'Jewelry (Grams)', value: 0, isZakatable: true },
];

export const DEFAULT_LIABILITIES: Liability[] = [
  { id: '1', name: 'Immediate Loans', amount: 0 },
];

export const TRANSLATIONS: Record<string, Translation> = {
  en: {
    title: 'Advanced Zakat Calculator',
    subtitle: 'Strictly based on Qur’an & Sahih Hadith',
    settings: 'Settings & Prices',
    fiqh: 'School of Thought (Fiqh)',
    language: 'Language',
    goldPrice: 'Gold Price (per gram)',
    silverPrice: 'Silver Price (per gram)',
    nisabBasis: 'Nisab Calculation Basis',
    assets: 'Assets (Wealth)',
    liabilities: 'Liabilities (Deductions)',
    calculate: 'Update Calculation',
    summary: 'Zakat Summary',
    totalZakat: 'Total Zakat Payable',
    netWealth: 'Net Zakatable Wealth',
    threshold: 'Nisab Threshold',
    eligible: 'Zakat is Obligatory (Fard)',
    notEligible: 'Zakat is NOT Obligatory',
    conditions: 'Shar\'ai Conditions',
    conditionMuslim: 'I am a Muslim',
    conditionOwnership: 'I have complete ownership',
    conditionHawl: 'One lunar year (Hawl) passed',
    conditionExplanations: {
      muslim: 'Zakat is an act of worship (Ibadah). It is obligatory only on free, sane, adult Muslims. (Quran 9:103)',
      ownership: 'You must have full possession and the right to dispose of the wealth. Wealth in blocked accounts or lost property is not Zakatable until retrieved.',
      hawl: 'A full lunar year (Hijri year ~354 days) must pass on the wealth exceeding Nisab. If wealth drops below Nisab during the year and recovers, the Hawl resets. (Sunan Ibn Majah 1792)',
    },
    hawlDate: 'Hawl Start Date (Hijri/Gregorian)',
    addAsset: '+ Add Asset',
    addLiability: '+ Add Liability',
    assetTypes: {
      cash: 'Cash / Bank',
      gold: 'Gold',
      silver: 'Silver',
      business: 'Business Stock',
      investment: 'Investments (Shares/MF)',
      crypto: 'Crypto Assets',
      jewelry: 'Jewelry',
    },
    liabilityTypes: {
      loan: 'Short-term Debt',
      bills: 'Pending Bills',
      emi: 'Current Year EMI',
    },
    references: 'References & Evidence',
    distribution: 'Distribution Categories (Asnaf)',
    printReport: 'Download PDF Report',
    currency: 'Currency',
    selectCurrency: 'Select Currency',
    gram: 'grams',
    notes: 'Scholar Notes: Hanafi considers jewelry Zakatable. Shafi exempts personal use jewelry unless excessive.',
    disclaimer: 'Disclaimer: This tool is for guidance. Please consult a local scholar for complex financial situations.',
    fetchRates: 'Fetch Live Rates',
    fetching: 'Fetching...',
    source: 'Source',
    aiSection: {
      title: 'Ask Zakat AI Scholar',
      placeholder: 'Ask a question about Zakat rules...',
      send: 'Ask',
      disclaimer: 'AI responses are for guidance only based on general rules. Consult a local scholar for complex personal fatwas.',
      welcome: 'As-salamu alaykum! I am your AI Zakat assistant. How can I help you understand Zakat rules today?',
    },
    customization: {
      title: 'Customize Report',
      preparedBy: 'Prepared By / Organization',
      uploadLogo: 'Upload Logo',
      addNotes: 'Personal Notes / Remarks',
      notesPlaceholder: 'Add any specific notes about this calculation...',
      qrLabel: 'Scan for Zakat Guide',
    },
    history: {
      title: 'Zakat History & Arrears',
      subtitle: 'Track past records and calculate unpaid zakat',
      saveBtn: 'Save to History',
      empty: 'No history records found.',
      savedMsg: 'Record saved successfully!',
      recordDate: 'Saved Date',
      hawlDate: 'Hawl Date',
      zakatAmount: 'Zakat Due',
      status: 'Status',
      markPaid: 'Mark Paid',
      markUnpaid: 'Mark Unpaid',
      delete: 'Delete',
      totalArrears: 'Total Pending Arrears',
    },
  },
  ur: {
    title: 'ایڈوانسڈ زکوٰۃ کیلکولیٹر',
    subtitle: 'قرآن اور صحیح حدیث کی روشنی میں',
    settings: 'ترتیبات اور قیمتیں',
    fiqh: 'فقہ (مسلک)',
    language: 'زبان',
    goldPrice: 'سونے کی قیمت (فی گرام)',
    silverPrice: 'چاندی کی قیمت (فی گرام)',
    nisabBasis: 'نصاب کا معیار',
    assets: 'اثاثے (املاک)',
    liabilities: 'واجبات (قرضہ جات)',
    calculate: 'حساب کریں',
    summary: 'زکوٰۃ کا خلاصہ',
    totalZakat: 'کل واجب الادا زکوٰۃ',
    netWealth: 'کل قابلِ زکوٰۃ مالیت',
    threshold: 'حدِ نصاب',
    eligible: 'زکوٰۃ فرض ہے',
    notEligible: 'زکوٰۃ فرض نہیں ہے',
    conditions: 'شرعی شرائط',
    conditionMuslim: 'میں مسلمان ہوں',
    conditionOwnership: 'مکمل ملکیت ہے',
    conditionHawl: 'ایک قمری سال گزر چکا ہے',
    conditionExplanations: {
      muslim: 'زکوٰۃ ایک عبادت ہے۔ یہ صرف عاقل، بالغ مسلمان پر فرض ہے۔ (قرآن 9:103)',
      ownership: 'مال پر آپ کا مکمل قبضہ اور اختیار ہونا ضروری ہے۔ گمشدہ یا منجمد مال پر زکوٰۃ نہیں جب تک وہ واپس نہ مل جائے۔',
      hawl: 'مال پر پورا ایک قمری سال گزرنا ضروری ہے۔ اگر سال کے دوران مال نصاب سے کم ہو جائے تو سال کا دورانیہ دوبارہ شروع ہوگا۔ (ابن ماجہ 1792)',
    },
    hawlDate: 'نصاب کی تاریخ (ہجری/عیسوی)',
    addAsset: '+ اثاثہ شامل کریں',
    addLiability: '+ ذمہ داری شامل کریں',
    assetTypes: {
      cash: 'نقد / بینک بیلنس',
      gold: 'سونا',
      silver: 'چاندی',
      business: 'تجارتی مال',
      investment: 'سرمایہ کاری (شیئرز)',
      crypto: 'کرپٹو کرنسی',
      jewelry: 'زیورات',
    },
    liabilityTypes: {
      loan: 'قرض',
      bills: 'بلز',
      emi: 'موجودہ سال کی قسط',
    },
    references: 'حوالہ جات',
    distribution: 'مصارفِ زکوٰۃ',
    printReport: 'رپورٹ ڈاؤن لوڈ کریں',
    currency: 'روپیہ',
    selectCurrency: 'کرنسی منتخب کریں',
    gram: 'گرام',
    notes: 'نوٹ: فقہ حنفی میں زیورات پر زکوٰۃ ہے، جبکہ فقہ شافعی میں استعمال کے زیورات پر عموماً زکوٰۃ نہیں ہے۔',
    disclaimer: 'وضاحت: یہ ٹول رہنمائی کے لیے ہے۔ پیچیدہ مسائل کے لیے مقامی عالم سے رجوع کریں۔',
    fetchRates: 'لائیو ریٹس حاصل کریں',
    fetching: 'تلاش جاری ہے...',
    source: 'ذریعہ',
    aiSection: {
      title: 'زکوٰۃ AI اسکالر سے پوچھیں',
      placeholder: 'زکوٰۃ کے مسائل کے بارے میں سوال پوچھیں...',
      send: 'پوچھیں',
      disclaimer: 'AI جوابات صرف عمومی رہنمائی کے لیے ہیں۔ پیچیدہ ذاتی فتاویٰ کے لیے مقامی عالم سے رجوع کریں۔',
      welcome: 'السلام علیکم! میں آپ کا AI زکوٰۃ معاون ہوں۔ آج میں زکوٰۃ کے مسائل میں آپ کی کیا مدد کر سکتا ہوں؟',
    },
    customization: {
      title: 'رپورٹ کو حسب ضرورت بنائیں',
      preparedBy: 'تیار کنندہ / تنظیم',
      uploadLogo: 'لوگو اپ لوڈ کریں',
      addNotes: 'ذاتی نوٹ / ریمارکس',
      notesPlaceholder: 'اس حساب کے بارے میں کوئی خاص نوٹ شامل کریں...',
      qrLabel: 'زکوٰۃ گائیڈ کے لیے اسکین کریں',
    },
    history: {
      title: 'زکوٰۃ کی تاریخ اور بقایا جات',
      subtitle: 'پچھلے ریکارڈ دیکھیں اور بقایا زکوٰۃ کا حساب لگائیں',
      saveBtn: 'ریکارڈ محفوظ کریں',
      empty: 'کوئی ریکارڈ موجود نہیں',
      savedMsg: 'ریکارڈ کامیابی سے محفوظ ہو گیا!',
      recordDate: 'تاریخ محفوظ',
      hawlDate: 'تاریخ نصاب',
      zakatAmount: 'واجب الزکوٰۃ',
      status: 'حیثیت',
      markPaid: 'ادا شدہ',
      markUnpaid: 'غیر ادا شدہ',
      delete: 'ختم کریں',
      totalArrears: 'کل بقایا جات',
    },
  },
  hi: {
    title: 'उन्नत ज़कात कैलकुलेटर',
    subtitle: 'कुरान और सहीह हदीस पर आधारित',
    settings: 'सेटिंग्स और कीमतें',
    fiqh: 'फ़िक़ह (विचारधारा)',
    language: 'भाषा',
    goldPrice: 'सोने की कीमत (प्रति ग्राम)',
    silverPrice: 'चांदी की कीमत (प्रति ग्राम)',
    nisabBasis: 'निसाब का आधार',
    assets: 'संपत्ति (Assets)',
    liabilities: 'देनदारियां (Liabilities)',
    calculate: 'गणना करें',
    summary: 'ज़कात सारांश',
    totalZakat: 'कुल देय ज़कात',
    netWealth: 'शुद्ध ज़कात योग्य धन',
    threshold: 'निसाब सीमा',
    eligible: 'ज़कात अनिवार्य है',
    notEligible: 'ज़कात अनिवार्य नहीं है',
    conditions: 'शरई शर्तें',
    conditionMuslim: 'मैं मुसलमान हूँ',
    conditionOwnership: 'पूर्ण स्वामित्व है',
    conditionHawl: 'एक चंद्र वर्ष पूरा हो गया है',
    conditionExplanations: {
      muslim: 'ज़कात एक इबादत है। यह केवल उन मुसलमानों पर अनिवार्य है जो समझदार और बालिग हैं। (कुरान 9:103)',
      ownership: 'धन पर आपका पूर्ण अधिकार और नियंत्रण होना चाहिए। खोई हुई या जब्त की गई संपत्ति पर तब तक ज़कात नहीं है जब तक वह वापस न मिल जाए।',
      hawl: 'धन पर एक पूरा चंद्र (हिजरी) वर्ष बीत जाना चाहिए। यदि वर्ष के दौरान धन निसाब् से कम हो जाता है, तो गणना फिर से शुरू होगी। (इब्न माजा 1792)',
    },
    hawlDate: 'आरंभ तिथि',
    addAsset: '+ संपत्ति जोड़ें',
    addLiability: '+ देनदारी जोड़ें',
    assetTypes: {
      cash: 'नकद / बैंक',
      gold: 'सोना',
      silver: 'चांदी',
      business: 'व्यापारिक माल',
      investment: 'निवेश (शेयर)',
      crypto: 'क्रिप्टो संपत्ति',
      jewelry: 'आभूषण',
    },
    liabilityTypes: {
      loan: 'ऋण',
      bills: 'लंबित बिल',
      emi: 'वर्तमान ईएमआई',
    },
    references: 'संदर्भ',
    distribution: 'ज़कात वितरण श्रेणियां',
    printReport: 'रिपोर्ट डाउनलोड करें',
    currency: 'मुद्रा',
    selectCurrency: 'मुद्रा चुनें',
    gram: 'ग्राम',
    notes: 'नोट: हनफ़ी में आभूषणों पर ज़कात है। शफ़ी में निजी उपयोग के आभूषणों पर आमतौर पर छूट है।',
    disclaimer: 'अस्वीकरण: यह उपकरण मार्गदर्शन के लिए है। कृपया जटिल मामलों के लिए स्थानीय विद्वान से परामर्श करें।',
    fetchRates: 'लाइव रेट प्राप्त करें',
    fetching: 'ला रहा है...',
    source: 'स्रोत',
    aiSection: {
      title: 'ज़कात AI स्कॉलर से पूछें',
      placeholder: 'ज़कात के नियमों के बारे में प्रश्न पूछें...',
      send: 'पूछें',
      disclaimer: 'AI उत्तर केवल सामान्य मार्गदर्शन के लिए हैं। जटिल व्यक्तिगत मामलों के लिए स्थानीय विद्वान से परामर्श करें।',
      welcome: 'अस्सलामु अलैकुम! मैं आपका AI ज़कात सहायक हूँ। आज मैं ज़कात के नियमों को समझने में आपकी कैसे मदद कर सकता हूँ?',
    },
    customization: {
      title: 'रिपोर्ट कस्टमाइज़ करें',
      preparedBy: 'तैयारकर्ता / संगठन',
      uploadLogo: 'लोगो अपलोड करें',
      addNotes: 'व्यक्तिगत नोट्स',
      notesPlaceholder: 'इस गणना के बारे में कोई विशेष नोट जोड़ें...',
      qrLabel: 'ज़कात गाइड के लिए स्कैन करें',
    },
    history: {
      title: 'ज़कात इतिहास और बकाया',
      subtitle: 'पिछले रिकॉर्ड देखें और बकाया ज़कात की गणना करें',
      saveBtn: 'इतिहास में सहेजें',
      empty: 'कोई इतिहास रिकॉर्ड नहीं मिला।',
      savedMsg: 'रिकॉर्ड सफलतापूर्वक सहेजा गया!',
      recordDate: 'सहेजने की तिथि',
      hawlDate: 'हौल तिथि',
      zakatAmount: 'देय ज़कात',
      status: 'स्थिति',
      markPaid: 'भुगतान किया',
      markUnpaid: 'अदत्त चिह्नित करें',
      delete: 'हटाएं',
      totalArrears: 'कुल बकाया बकाया',
    },
  },
  ar: {
    title: 'حاسبة الزكاة المتقدمة',
    subtitle: 'مبنية بدقة على القرآن وصحيح الحديث',
    settings: 'الإعدادات والأسعار',
    fiqh: 'المذهب الفقهي',
    language: 'اللغة',
    goldPrice: 'سعر الذهب (للجرام)',
    silverPrice: 'سعر الفضة (للجرام)',
    nisabBasis: 'معيار النصاب',
    assets: 'الأصول (الممتلكات)',
    liabilities: 'الخصوم (الديون)',
    calculate: 'تحديث الحساب',
    summary: 'ملخص الزكاة',
    totalZakat: 'إجمالي الزكاة المستحقة',
    netWealth: 'صافي الثروة الزكوية',
    threshold: 'حد النصاب',
    eligible: 'الزكاة واجبة',
    notEligible: 'الزكاة غير واجبة',
    conditions: 'الشروط الشرعية',
    conditionMuslim: 'أنا مسلم',
    conditionOwnership: 'لدي ملكية تامة',
    conditionHawl: 'حال الحول (عام قمري كامل)',
    conditionExplanations: {
      muslim: 'الزكاة عبادة، وهي واجبة فقط على المسلم الحر العاقل البالغ. (القرآن 9:103)',
      ownership: 'يجب أن يكون لديك ملكية تامة وحق التصرف في المال. المال المفقود أو المجمد لا زكاة فيه حتى يعود.',
      hawl: 'يجب أن يمر عام قمري كامل (حوالي 354 يومًا) على المال الذي بلغ النصاب. إذا نقص المال عن النصاب أثناء الحول، ينقطع الحول. (ابن ماجه 1792)',
    },
    hawlDate: 'تاريخ بداية الحول (هجري/ميلادي)',
    addAsset: '+ إضافة أصل',
    addLiability: '+ إضافة دين',
    assetTypes: {
      cash: 'نقد / بنك',
      gold: 'ذهب',
      silver: 'فضة',
      business: 'عروض تجارة',
      investment: 'استثمارات (أسهم)',
      crypto: 'عملات رقمية',
      jewelry: 'مجوهرات / حلي',
    },
    liabilityTypes: {
      loan: 'ديون قصيرة الأجل',
      bills: 'فواتير مستحقة',
      emi: 'أقساط العام الحالي',
    },
    references: 'الأدلة والمراجع',
    distribution: 'مصارف الزكاة',
    printReport: 'تحميل التقرير (PDF)',
    currency: 'العملة',
    selectCurrency: 'اختر العملة',
    gram: 'جرام',
    notes: 'ملاحظة: المذهب الحنفي يوجب الزكاة في الحلي. الشافعي والجمهور يعفون عن حلي الاستعمال الشخصي ما لم يتجاوز حد الإسراف.',
    disclaimer: 'تنويه: هذه الأداة للإرشاد فقط. يرجى استشارة عالم محلي للحالات المالية المعقدة.',
    fetchRates: 'جلب الأسعار الحية',
    fetching: 'جاري البحث...',
    source: 'المصدر',
    aiSection: {
      title: 'اسأل المساعد الذكي للزكاة',
      placeholder: 'اطرح سؤالاً حول أحكام الزكاة...',
      send: 'إرسال',
      disclaimer: 'ردود الذكاء الاصطناعي للإرشاد العام فقط. استشر عالمًا محليًا للفتاوى الشخصية المعقدة.',
      welcome: 'السلام عليكم! أنا مساعدك الذكي في أحكام الزكاة. كيف يمكنني مساعدتك اليوم؟',
    },
    customization: {
      title: 'تخصيص التقرير',
      preparedBy: 'إعداد / المنظمة',
      uploadLogo: 'رفع الشعار',
      addNotes: 'ملاحظات شخصية',
      notesPlaceholder: 'أضف أي ملاحظات خاصة حول هذا الحساب...',
      qrLabel: 'امسح للوصول لدليل الزكاة',
    },
    history: {
      title: 'سجل الزكاة والمتأخرات',
      subtitle: 'تتبع السجلات السابقة وحساب الزكاة غير المدفوعة',
      saveBtn: 'حفظ في السجل',
      empty: 'لا توجد سجلات محفوظة.',
      savedMsg: 'تم حفظ السجل بنجاح!',
      recordDate: 'تاريخ الحفظ',
      hawlDate: 'تاريخ الحول',
      zakatAmount: 'الزكاة المستحقة',
      status: 'الحالة',
      markPaid: 'تم الدفع',
      markUnpaid: 'غير مدفوع',
      delete: 'حذف',
      totalArrears: 'إجمالي المتأخرات',
    },
  },
};